name: Frontend CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_API_URL: https://nextjs-movie-backend-gfda.onrender.com/api
      CYPRESS_baseUrl: http://localhost:3000

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Wait for Render backend to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: https://nextjs-movie-backend-gfda.onrender.com/api/movies/popular
          timeout: 60

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
